### PR TITLE
Configure pytest warning control in pyproject.toml

### PR DESCRIPTION
**Pull request by dlax**
This reduces duplication and makes the configuration available when
testing outside CI.

### CODE REVIEW

**Comment by dvarrazzo** [comment]
Oh thank you. I was thinking that the errors on warning would be welcome at dev time indeed.

I was also thinking that the --color=yes can be added as an env var available to all the jobs in the CI. I'll make that change...

**Comment by dlax** [comment]
> I was also thinking that the --color=yes can be added as an env var available to all the jobs in the CI. I'll make that change...

Maybe it's doable with PYTEST_ADDOPTS environment variable.

**Comment by dvarrazzo** [comment]
> Maybe it's doable with PYTEST_ADDOPTS environment variable.

Yes, I'm pushing just that: 195b39b32765a57376f1c82fa1cbdd53f90b274c

**Comment by dlax** [comment]
> > Maybe it's doable with PYTEST_ADDOPTS environment variable.
> 
> Yes, I'm pushing just that: [195b39b](https://github.com/psycopg/psycopg/commit/195b39b32765a57376f1c82fa1cbdd53f90b274c)

You might also need to tell tox to pass the variable (with `passenv` if I remember correctly); or does it work as is already?

**Comment by dvarrazzo** [comment]
It knows already:

https://github.com/psycopg/psycopg/blob/5e4689522327631772f931d9b8ac0917f4b54895/psycopg/tox.ini#L9

**Pull request merged**
