### PR TITLE
Build Python 3.13 wheels

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Related:

- Closes https://github.com/psycopg/psycopg/issues/889

### CODE REVIEW

**Comment by dvarrazzo** [comment]
Thank you, looks good, I see your test workflows [here](https://github.com/edgarrmondragon/psycopg/actions).

Can you please run a [binary package workflow](https://github.com/psycopg/psycopg/actions/workflows/packages-bin.yml) on your branch?

Could you please update the metadata in the three `psycopg*/setup.cfg` files and in `docs/basic/install.rst`? Also a note for the 3.2.2 release in `docs/news.txt` would be useful.

Thank you very much!

**Comment by dvarrazzo** [comment]
I have another chore: there's an [internal document](https://github.com/psycopg/psycopg/blob/master/docs/release.rst) that specifies how to make a release (which I see I should clean up, there are a few stale info) and what to change when a major Postgres release is created. 

Could you pleas add a section there to document what to do when a major Python release is added, where you pretty much list out the places that you needed to change in this MR?

Thank you very much!

**Comment by edgarrmondragon** [comment]
> I have another chore: there's an [internal document](https://github.com/psycopg/psycopg/blob/master/docs/release.rst) that specifies how to make a release (which I see I should clean up, there are a few stale info) and what to change when a major Postgres release is created.
> 
> Could you pleas add a section there to document what to do when a major Python release is added, where you pretty much list out the places that you needed to change in this MR?
> 
> Thank you very much!

Done in 1dadec7dbb1d2f3807c4700ec5579377b9a5b092.

Let me know if anything's missing.

**Comment by edgarrmondragon** [comment]
Python 3.13.0rc2, so it'd be nice to start publishing wheels :)

Let me know if I can do anything to get this get merged.

**Comment by dvarrazzo** [comment]
Hello, I'm sorry, I'm in the middle of a few more urgent jobs. I'll see what I can do.

**Pull request merged**
