### PR TITLE
Issue 456 - base _queries.pyx which compiles successfully

### PR DESCRIPTION
**Pull request by jmallad**
I got ahead of myself a bit, my apologies. I split off a new branch, and reset it to the first point at which I had a version of _queries.pyx that successfully builds. Once this passes tests, I will start including C optimizations one at a time.

### CODE REVIEW

**Comment by jmallad** [comment]
Which version of Cython are we targeting?
I just found [this](https://cython.readthedocs.io/en/stable/src/quickstart/cythonize.html) page: that is very different from the [latest](https://cython.readthedocs.io/en/latest/src/quickstart/cythonize.html) version. I think this might clear up why I'm having so much trouble with the type annotations. I have Cython 0.29.33 according to "cython --version" run in my virtualenv.

**Comment by dvarrazzo** [comment]
Ah I see. We are targeting Cython 3.0.0a11 or greater at the moment. The stable versions of Cython don't generate code for the current Python versions.

**Comment by jmallad** [comment]
I can compile and import psycopg_c on its own now. But, it doesn't seem to be structured correctly. It's not exposing the "_psycopg" module that has most of the code. 

> >>> import psycopg
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/zamnedix/Projects/psycopg/venv/lib/python3.9/site-packages/psycopg-3.2.0.dev1-py3.9.egg/psycopg/__init__.py", line 10, in <module>
>     from . import types
>   File "/home/zamnedix/Projects/psycopg/venv/lib/python3.9/site-packages/psycopg-3.2.0.dev1-py3.9.egg/psycopg/types/__init__.py", line 7, in <module>
>     from .. import _typeinfo
>   File "/home/zamnedix/Projects/psycopg/venv/lib/python3.9/site-packages/psycopg-3.2.0.dev1-py3.9.egg/psycopg/_typeinfo.py", line 14, in <module>
>     from . import sql
>   File "/home/zamnedix/Projects/psycopg/venv/lib/python3.9/site-packages/psycopg-3.2.0.dev1-py3.9.egg/psycopg/sql.py", line 17, in <module>
>     from ._transformer import Transformer
>   File "/home/zamnedix/Projects/psycopg/venv/lib/python3.9/site-packages/psycopg-3.2.0.dev1-py3.9.egg/psycopg/_transformer.py", line 12, in <module>
>     from ._cmodule import _psycopg
>   File "/home/zamnedix/Projects/psycopg/venv/lib/python3.9/site-packages/psycopg-3.2.0.dev1-py3.9.egg/psycopg/_cmodule.py", line 16, in <module>
>     from psycopg_c import _psycopg as _psycopg
>   File "psycopg_c/_psycopg.pyx", line 1, in init psycopg_c._psycopg
> ModuleNotFoundError: No module named 'psycopg_c._psycopg.transform'; 'psycopg_c._psycopg' is not a package
> 

I can't figure out what I did to cause this. I have "include "_psycopg/transform.pyx" in _psycopg.pyx; I cimported transform in __init__.pxd. I haven't changed much else, but when I build and test from master it works, so I know it's something I did.

**Comment by dvarrazzo** [comment]
Yesterday I managed to build this branch and to pass the tests.

Do you want to take a look at the commits in the [branch fix-456](https://github.com/psycopg/psycopg/tree/fix-456)? The first commit is your code, squashed (as of yesterday), and has your attribution. The others are fixes I added on top to make it pass the tests. See all the changes [here](https://github.com/psycopg/psycopg/compare/master...fix-456).

**Pull request closed without merging**
